exports.city = [
    {
        name: "Delhi",
        cityName: "Lal Kot/Qila Rai ",
        Timg: "ABC",
        desc: " The Red Fort is a historic fort in the city of Delhi in India that served as the main residence of the Mughal Emperors. Emperor Shah Jahan commissioned construction of the Red Fort on 12 May 1638, when he decided to shift his capital from Agra to Delhi.",
        Address: " Netaji Subhash Marg, Lal Qila, Chandni Chowk, New Delhi, Delhi 110006",
        Phone: " 011 2327 7705",
        Architect: " Ustad Ahmad Lahouri",
        Built: " 12 May 1639 – 6 April 1648; 373 years ago",
        Architectural: " style(s): Indo-Islamic, Mughal Designated as world heritage site: 2007 (31st session)",
        StateParty: " India",
        HeightOrArea: " 18–33 m (59–108 ft)",
        Link: "https://en.wikipedia.org/wiki/Qila_Rai_Pithora",
        img: "./Image/Delhi/redFort/red2.jpg",
        img2: "./Image/Delhi/redFort/red3.jpg",
        img3: "./Image/Delhi/redFort/red4.jpg",
        img4: "./Image/Delhi/redFort/red5.jpg",
    },
    {
        name: "Delhi",
        cityName: "Mehrauli",
        desc: " Mehrauli is a neighbourhood in South Delhi, a district of Delhi in India. It represents a constituency in the legislative assembly of Delhi. The area is located close to Gurgaon and next to Vasant Kunj. Naresh Yadav of Aam Aadmi Party is the current MLA from Mehrauli The iron pillar of Delhi is a structure 23 feet 8 inches high with 16 inches diameter that was constructed by Chandragupta II",
        Address: "South district,Pithora",

        Phone: " 011 2327 7705",
        Architect: " Tanwar",
        Built: " 0000000",
        Architectural: " style(s): Indo-Islamic, Mughal Designated as world heritage site: 2007 (31st session)",
        StateParty: " India",
        HeightOrArea: " 15 feet",
        Link: "https://en.wikipedia.org/wiki/Mehrauli",
        img: "./Image/Delhi/Mehrauli/meh1.jpg",
        img2: "./Image/Delhi/Mehrauli/meh2.jpg",
        img3: "./Image/Delhi/Mehrauli/meh3.jpg",
        img4: "./Image/Delhi/Mehrauli/meh4.jpg",
    },
    // { 
    //     name:"Delhi",
    //     cityName: "Siri",
    //     Timg: "ABC",
    //     desc: " Siri Fort, in the city of New Delhi, was built during the rule of Alauddin Khilji, the ruler of the Delhi Sultanate, to defend the city from the onslaught of the Mongols. It was the second of the seven cities of medieval Delhi built around 1303 (stated to be the first entirely constructed by Turks), which at present is seen only in ruins with a few remnants (pictured)[1][2]Near the Siri Fort ruins modern auditoriums, the Asian Games Village Complex and residential and commercial establishments fill the modern landscape between the Khel Gaon Marg and the Aurobindo Marg in the heart of South Delhi",

    //     Address: " South district",
    //     Phone:" 011 2327 7705",
    //     Architect:" Khilji Dynasty",
    //     Built: " c. 1303",
    //     Architectural : " style(s): Indo-Islamic, Mughal Designated as world heritage site: 2007 (31st session)",
    //     StateParty: " Indian Government",
    //     HeightOrArea:" 20 feet OR  1.7 km2 (0.7 sq mi).",
    //     Link:"https://en.wikipedia.org/wiki/Siri_Fort",
    //     img:"./Image/Delhi/masjid.jpg",
    //     img2:"",
    //     img3:"",
    //     img4:"",
    // },
    // { 
    //     name:"Delhi",
    //     cityName: "Tughlakabad",
    //     Timg: "ABC",
    //     desc: " Tughlaqabad Fort is a ruined fort in Delhi, built by Ghiyas-ud-din Tughlaq, the founder of Tughlaq dynasty, of the Delhi Sultanate of India in 1321, as he established the third historic city of Delhi, which was later abandoned in 1327. It lends its name to the nearby Tughlaqabad residential-commercial area as well as the Tughlaqabad Institutional Area. Tughlaq also built Qutub-Badarpur Road, which connected the new city to the Grand Trunk Road. The road is now known as Mehrauli-Badarpur Road.[1] The entry fee for the Fort is Rs. 20 for Indians.[2] Also, nearby is Dr. Karni Singh Shooting Range and Okhla Industrial Area.",

    //     Address: " Delhi",
    //     Phone:" 011 2327 7705",
    //     Architect:"	Ghiyas-ud-din-Tughlaq",
    //     Built: " 14th century",
    //     Architectural : " style(s): Indo-Islamic, Mughal Designated as world heritage site: 2007 (31st session)",
    //     StateParty: " Indian Government",
    //     HeightOrArea:" Not Mentioned",
    //     Link:"https://en.wikipedia.org/wiki/Tughlaqabad_Fort",
    //     img:"./Image/Delhi/kabir.jpg",
    //     img2:"",
    //     img3:"",
    //     img4:"",
    // },
    {
        name: "Kolkatta",
        cityName: "Victoria Memorial",
        desc: "The Victoria Memorial is a large marble building in Kolkata, which was built between 1906 and 1921. It is dedicated to the memory of Empress Victoria, and is now a museum under the auspices of the Ministry of Culture. The memorial lies on the Maidan and is one of the famous monuments of Kolkata",

        Address: " 	Jawaharlal Nehru Road, Kolkata, West Bengal,  India",
        Phone: " 011 2327 7705",
        Architect: "	William Emerson , Vincent Esch",
        Built: " 1905",
        Architectural: " Indo-Saracenic revivalist ,The Victoria Memorial was mainly funded by British Officials.",
        StateParty: " Indian Government",
        HeightOrArea: " 57 acres(Area)",
        Link: "https://en.wikipedia.org/wiki/Victoria_Memorial,_Kolkata",
        img: "./Image/Kolkatta/victoria/victoria1.jpg",
        img2: "./Image/Kolkatta/victoria/victoria2.jpg",
        img3: "./Image/Kolkatta/victoria/victoria3.jpg",
        img4: "./Image/Kolkatta/victoria/victoria4.jpg",

    },
    {
        name: "Kolkatta",
        cityName: "Howrah Bridge",
        desc: "The bridge is one of four on the Hooghly River and is a famous symbol of Kolkata and West Bengal. The other bridges are the Vidyasagar Setu, the Vivekananda Setu and the newly built Nivedita Setu. It weathers the storms of the Bay of Bengal region, carrying a daily traffic of approximately 100,000 vehicles and possibly more than 150,000 pedestrians, easily making it the busiest cantilever bridge in the world. The third-longest cantilever bridge at the time of its construction, the Howrah Bridge is currently the sixth-longest bridge of its type in the world",
        Address: " 		Howrah and Kolkata",
        Phone: " 011 2327 7705",
        Architect: " Braithwaite, Burn & Jessop Construction Company",
        Built: " Construction start	1936 and Construction end 1942",
        Architectural: " Suspension type Balanced Cantilever and truss arch",
        StateParty: " Kolkatta/Indian Government",
        HeightOrArea: " 705 m (2,313.0 ft),	71 ft (21.6 m) with two footpaths of 15 ft (4.6 m) on either side[5]",
        Link: "https://en.wikipedia.org/wiki/Howrah_Bridge",
        img: "./Image/Kolkatta/Hawrah-Bridge/bridge1.jpg",
        img2: "./Image/Kolkatta/Hawrah-Bridge/bridge2.jpg",
        img3: "./Image/Kolkatta/Hawrah-Bridge/bridge3.jpg",
        img4: "./Image/Kolkatta/Hawrah-Bridge/bridge4.jpg",
    },
    // {
    //     name:"Kolkatta",
    //     cityName: "Siri",
    //     Timg: "ABC",
    //     desc: "Siri Fort, in the city of New Delhi, was built during the rule of Alauddin Khilji, the ruler of the Delhi Sultanate",
    // },
    // {
    //     name:"Kolkatta",
    //     cityName: "Tughlakabad",
    //     Timg: "ABC",
    //     desc: "Tughlakabad Vidhan Sabha constituency is one of the 70 Vidhan Sabha constituencies of the National Capital Territory in northern India"
    // },
    // {
    //     name:"Kolkatta",
    //     cityName: "New Delhi",
    //     Timg: "ABC",
    //     desc: " New Delhi is the seat of all three branches of the government of India, hosting the Rashtrapati Bhavan, Parliament House, and the Supreme Court of India"
    // },
    {
        name: "Gujrat",
        cityName: "Rani Ki Vav",
        desc: "Rani ki Vav or Ranki vav (lit. 'Queen’s stepwell') is a stepwell situated in the town of Patan in Gujarat state of India. It is located on the banks of Saraswati river. Its construction is attributed to Udayamati, daughter of Khengara of Saurashtra, queen of the 11th-century Solanki dynasty and spouse of Bhima I. Silted over, it was rediscovered in 1940s and restored in 1980s by the Archaeological Survey of India. It has been listed as one of UNESCO's World Heritage Sites since 2014.",
        Address: " 	Patan, Patan district, Gujarat, India,",
        Phone: " 011 2327 7705",
        Architect: " Udayamati, the daughter of Naravaraha Khengara",
        Built: " 1304",
        Architectural: " Maru-Gurjara architecture style, reflecting mastery of this complex technique and beauty of detail and proportions",
        StateParty: " Gujrat/Indian Government",
        HeightOrArea: " 4.68 ha (11.6 acres)",
        Link: "https://en.wikipedia.org/wiki/Rani_ki_vav",
        img: "./Image/Gujrat/Rani_ki_vav/vav2.jpg",
        img2: "./Image/Gujrat/Rani_ki_vav/vav1.jpg",
        img3: "./Image/Gujrat/Rani_ki_vav/vav3.jpg",
        img4: "./Image/Gujrat/Rani_ki_vav/vav4.jpg",
    },
    {
        name: "Gujrat",
        cityName: "Statue of Unity",
        desc: "The Statue of Unity is a colossal statue of Indian statesman and independence activist Vallabhbhai Patel, who was the first Deputy Prime Minister and Home Minister of independent India and an adherent of Mahatma Gandhi during the nonviolent Indian Independence movemen",
        Address: " 	 Sardar Sarovar Dam, Statue of Unity Rd, Kevadia, Gujarat 393155",
        Phone: " 1800 233 6600",
        Architect: " Ram V. Sutar",
        Built: "  and was inaugurated by Indian Prime Minister Narendra Modi on 31 October 2018, the 143rd anniversary of Sardar Patel's birth",
        Architectural: " Maru-Gurjara architecture style, reflecting mastery of this complex technique and beauty of detail and proportions",
        StateParty: " Gujrat/Indian Government",
        HeightOrArea: " 182 m(Height)",
        Link: "https://en.wikipedia.org/wiki/Statue_of_Unity",
        img: "./Image/Gujrat/StatueOfUnity/unity1.jpg",
        img2: "./Image/Gujrat/StatueOfUnity/unity2.jpg",
        img3: "./Image/Gujrat/StatueOfUnity/unity3.jpg",
        img4: "./Image/Gujrat/StatueOfUnity/unity4.jpg",
    },
    {
        name:"Gujrat",
        cityName: "Sun Temple ",
        desc:"The Sun Temple is a Hindu temple dedicated to the solar deity Surya located at Modhera village of Mehsana district, Gujarat, India. It is situated on the bank of the river Pushpavati. It was built after 1026-27 CE during the reign of Bhima I of the Chaulukya dynasty",

        Address: " 	 On, Mehsana - Becharaji Rd, Highway, Modhera, Gujarat 384212",
        Phone: " 1800 233 6600",
        Architect: " Bhima I",
        Built: "  1026",
        Architectural: " Māru-Gurjara architecture completed(after 1026-27 CE (shrine proper))",
        StateParty: " Gujrat/Indian Government",
        HeightOrArea: " Not Mension",
        Link: "https://en.wikipedia.org/wiki/Sun_Temple,_Modhera",
        img: "./Image/Gujrat/SuryaTemple/surya1.jpg",
        img2: "./Image/Gujrat/SuryaTemple/surya2.jpg",
        img3: "./Image/Gujrat/SuryaTemple/surya3.jpg",
        img4: "./Image/Gujrat/SuryaTemple/surya4.jpg",

    },
    // {
    //     name:"Gujrat",
    //     cityName: "Siri",
    //     Timg: "ABC",
    //     desc: "Siri Fort, in the city of New Delhi, was built during the rule of Alauddin Khilji, the ruler of the Delhi Sultanate",
    // },
    // {
    //     name:"Gujrat",
    //     cityName: "Amazing Water Park",
    //     Timg: "ABC",
    //     desc: "Tughlakabad Vidhan Sabha constituency is one of the 70 Vidhan Sabha constituencies of the National Capital Territory in northern India"
    // },
    // {
    //     name:"Gujrat",
    //     cityName: "Adlaj Step-Well",
    //     Timg: "ABC",
    //     desc: " New Delhi is the seat of all three branches of the government of India, hosting the Rashtrapati Bhavan, Parliament House, and the Supreme Court of India"
    // },
    // {
    //     name:"Gujrat",
    //     cityName: "Polo Forest",
    //     Timg: "ABC",
    //     desc: " New Delhi is the seat of all three branches of the government of India, hosting the Rashtrapati Bhavan, Parliament House, and the Supreme Court of India"
    // },
    // { 
    //     name:"mumbai",
    //     cityName: "Lal Kot or Qila Rai Pithora",
    //     Timg: "ABC",
    //     desc: "The Red Fort is a historic fort in the city of Delhi (in Old Delhi) in India that served as the main residence of the Mughal Emperors",
    // },
    // { 
    //     name:"mumbai",
    //     cityName: "Mehrauli",
    //     Timg: "ABC",
    //     desc: "The iron pillar of Delhi is a structure 23 feet 8 inches high with 16 inches diameter that was constructed by Chandragupta II",
    // },
    // { 
    //     name:"mumbai",
    //     cityName: "Siri",
    //     Timg: "ABC",
    //     desc: "Siri Fort, in the city of New Delhi, was built during the rule of Alauddin Khilji, the ruler of the Delhi Sultanate",
    // },
    // { 
    //     name:"mumbai",
    //     cityName: "Tughlakabad",
    //     Timg: "ABC",
    //     desc: "Tughlakabad Vidhan Sabha constituency is one of the 70 Vidhan Sabha constituencies of the National Capital Territory in northern India"
    // },
    // { 
    //     name:"mumbai",
    //     cityName: "New Delhi",
    //     Timg: "ABC",
    //     desc: " New Delhi is the seat of all three branches of the government of India, hosting the Rashtrapati Bhavan, Parliament House, and the Supreme Court of India"
    // },

]